olmps/memo

README.md

This is a implementation proposed by @AugustoSavi on issue #5 to solve the broken link on README.md referring the README.ptbr

Fix broken README.ptbr link

---

README_ptbr.md

Correções ortográficas:
- Adição de acento para a palavra depend**ê**ncias.
- Alteração de `.` para `;` como delimitador final para lista/sumário, seguindo o padrão dos outros tópicos.

Fix typo on README_ptbr.md

---

.github/workflows/flutter-ci.yml

Setup of CI with github actions 
**Proposed steps**:
- Installation of flutter and flutter dependences
- Execution of flutter formatter, analyser and linter
- Execution of tests
**Trigger**: on pull requests
For the future will be interesting add the CD setup with `fastlane` as the mentioned by @matuella on issue #16.
Some details would be important set here too, like flutter version or when the process will be trigged. 
This setup was inspired on this [gist](https://gist.github.com/aagarwal1012/eb2551683d81cf47d60868ab607520b1)
This changes have been discussed on issue #16  …

Add github actions workflow

---

.github/workflows/flutter-ci.yml
README.md
README_ptbr.md
analysis_options.yaml
lib/application/coordinator/routes_coordinator.dart
pubspec.lock
pubspec.yaml

* Adds CodeCov to Github Actions Workflow and add Codecov badge into Readme. For the Badge link to work, you need to activate the repository on Codecov. I activated the repository in my Codecov account and it is working perfectly, as you can see in the main branch of my repository
* Adds CodeCov to Github Actions Workflow #26

Add CodeCov to Github Actions Workflow #26

---

test/data/database_repository_test.dart

* Add test for listenAll method #30

Add test for listenAll method

---

README.md

Adding Sponsors to README

---

README.md
README_ptbr.md

This PR is adding bullet formation to the list of Sponsors, and complementing the EN doc with sponsors description.

[Documentation] Sponsors description and formatting break lines with bulleted list

---

.github/workflows/pull-request.yml
CHANGELOG.md
lib/application/pages/details/collection_details_page.dart
lib/core/faults/exceptions/base_exception.dart
pubspec.lock
pubspec.yaml

Home indicator fix

---

lib/application/app.dart
lib/application/constants/strings.dart

- Adds missing ToS link;
- ~Updates AppRoot to StatefulWidget and makes sure it only initializes its dependencies once~ Updates missing docs on `/application` - relates to #120.

Application-wide fixes

---

CHANGELOG.md
lib/application/pages/execution/execution_terminal.dart

Removes `QuillEditor` cursor

---

.github/workflows/pull-request.yml
.github/workflows/release.yml
android/fastlane/Fastfile
ios/fastlane/Fastfile

Relates to https://github.com/olmps/memo/issues/94

Worfklows performance improvements

---

CHANGELOG.md
lib/application/widgets/material/asset_icon_button.dart

Updates `AssetIconButton` default insets padding

---

ios/Runner.xcodeproj/project.pbxproj
ios/Runner/en.lproj/InfoPlist.strings

Removes english localization from iOS project

---

lib/application/constants/strings.dart
lib/application/pages/execution/collection_execution_page.dart
lib/application/theme/memo_theme_colors.dart
lib/application/theme/memo_theme_data.dart
lib/application/theme/theme_controller.dart
lib/application/utils/bottom_sheet.dart
lib/application/widgets/theme/destructive_button.dart
lib/application/widgets/theme/negative_button.dart
lib/application/widgets/theme/secondary_button.dart

It also adds a new color swatch named `negative`

Replace `AlertDialog` by `showModalBottomSheet`

---

lib/application/pages/execution/collection_execution_page.dart
lib/application/pages/execution/execution_terminal.dart

Fixes https://github.com/olmps/memo/issues/172

Fixes SafeArea in `ExecutionTerminal`

---

CHANGELOG.md
pubspec.lock
pubspec.yaml

Bumped `pubspec` to reflect the animation jank fix.

0.2.0 rc.1

---

lib/application/constants/animations.dart
lib/application/constants/strings.dart
lib/application/pages/execution/collection_execution_page.dart
lib/application/pages/execution/execution_terminal.dart
lib/application/view-models/execution/collection_execution_vm.dart

This solves all execution related bugs.

Refactors `ExecutionTerminal` exposing a `TerminalController`

---

CHANGELOG.md
lib/application/pages/details/collection_details_page.dart
lib/application/pages/execution/collection_execution_page.dart
lib/application/pages/execution/completed_execution_contents.dart
lib/application/pages/execution/execution_terminal.dart
lib/application/pages/home/collections/collections_page.dart
lib/application/widgets/theme/custom_button.dart
lib/application/widgets/theme/destructive_button.dart
test/application/widgets/theme/custom_button_test.dart
test/utils/widget_pump.dart

*Faça aqui uma breve descrição das alterações que esse PR faz e o porquê / Describe the changes proposed in this PR and their motivation:*
Creates visually opinionated buttons that that will be used throughout the application. This is necessary because the buttons used in memo app doesn't follow the Material's guidelines.
*Liste pelo menos um issue relacionado à este PR. / List at least one open issue related to this PR:*
Related to [[Component] Custom Button](https://github.com/olmps/memo/issues/224).
tests - …

Creates custom buttons

---

.github/workflows/analyze-tests.yml
.github/workflows/android-build.yaml
.github/workflows/ios-build.yaml

Improves the performance from the build workflows by splitting the process into 3 distinct workflows:
1. `Analyze & Tests`: Run `flutter analyze` and `flutter test` in any PR that points to `main`.
2. `iOS Build`: Run `flutter build ios` in PRs that point to `main` and have changes in `ios/` folder.
3. `Android Build`: Run `flutter build appbundle` in PRs that point to `main` and have changes in `android/` folder.

Workflows improvements

---

.github/workflows/update-collections.yml
firebase/collections/bdd_fundamentos_01.json
firebase/collections/comecando_com_git.json
firebase/collections/ecossistema_do_flutter.json
firebase/collections/fundamentos_scrum.json
firebase/collections/guia_scrum.json
firebase/collections/kotlin_fundamentos_01.json
firebase/collections/manifesto_agil.json
firebase/collections/swift_fundamentos_01.json
firebase/package.json
firebase/src/core/data/schemas/entities-schemas/collection-resources.json
firebase/src/core/domain/models/collection.ts
firebase/src/scripts/sync-collections.ts
firebase/test/collections/integrity-check.spec.ts

Also adds updated - added `resources` and made other small adjustments - collections to `collections/` folder.

Adds collections integrity unit tests

---

firebase/test/core/data/repositories/local-collections-repository.spec.ts
firebase/test/core/data/repositories/memos-repository.spec.ts
firebase/test/core/data/repositories/stored-collections-repository.spec.ts
firebase/test/core/data/schemas/memo.spec.ts
firebase/test/core/domain/models/memo.spec.ts
firebase/test/core/domain/models/stored-public-collection.spec.ts
firebase/test/entity-tester.ts

Fixes missing `assert.reject` awaits, which was causing false-positive when running tests scripts

Fixes assertions awaits
